@host = https://localhost
@port = 7044

POST {{host}}:{{port}}/shorten
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "code": "rammstein",
    "longUrl": "https://www.rammstein.de/de/konzerte/gelsenkirchen-27-07-2024/"
}

###

POST {{host}}:{{port}}/shorten
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "code": "swiftie",
    "longUrl": "https://www.fansale.de/tickets/all/taylor-swift/448410"
}

###

GET https://localhost:7044/goto/rammstein

###

GET https://localhost:7044/shortenedurls
